version: '3.3'
services:
  db_mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    container_name: db_mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "mypassword@@aabbcc123"
      ACCEPT_EULA: "Y"

  web_develop:
    depends_on:
      - db_mssql
    image: "mcr.microsoft.com/dotnet/sdk:3.1"
    container_name: web_develop
    environment:
      PATH: "$PATH:/root/.dotnet/tools"
    volumes:
      - ./src:/app 
    command: dotnet tool install --global dotnet-ef --version 3.1
    command: dotnet restore /app/Avanade.Challenge.Web
    command: dotnet build /app/Avanade.Challenge.Web
    command: dotnet ef database update --project /app/Avanade.Challenge.Infra.Database
    command: dotnet run --project /app/Avanade.Challenge.Web run --urls "http://0.0.0.0:8080"   
    ports:
      - "80:8080"
    links:
      - "db_mssql:database"

volumes:
  db_data: {} 