version: '3.3'
services:
    sql_lojasintegradas:
      image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
      container_name: sql_lojasintegradas
      ports:
        - "1434:1433"
      environment:
        SA_PASSWORD: "aaabbbccc1234@@asdfas123"
        ACCEPT_EULA: "Y"
  
    api_backend:
      depends_on:
        - sql_lojasintegradas
      image: "mcr.microsoft.com/dotnet/sdk:3.1"
      container_name: api_backend
      environment:
        PATH: "$PATH:/root/.dotnet/tools"
      volumes:
        - ./src/backend:/app  
      command: dotnet tool install -g nbgv
      command: dotnet restore /app/LojasIntegrada.Challenge.Api
      command: dotnet build /app/LojasIntegrada.Challenge.Api 
      command: dotnet run --project /app/LojasIntegrada.Challenge.Api run --urls "http://0.0.0.0:8080"   
      ports:
        - "5000:8080"
      links:
        - "sql_lojasintegradas:database" 

    web_react:
      depends_on:
        - api_backend
      image: "nginx"
      container_name: web_react
      volumes:
        - ./src/frontend:/app
        - ./src/frontend/conf.d:/etc/nginx/conf.d/
      ports:
        - "5001:80"

volumes:
  db_data: {}
  web_dev: {}
